sudo: required
services: 
 - docker
 
deploy:
 provider: elasticbeanstalk
 region: "us-west-2"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-west-2-106536797114" 
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_ACCESS_SECRET